version: '3.8'

services:
  jobmanager:
    image: flink:1.20.1-java17
    ports:
      - "8081:8081"
      - "6123:6123"  # Expose JobManager RPC port
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_PROPERTIES=jobmanager.rpc.address:jobmanager

  taskmanager:
    image: flink:1.20.1-java17
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - FLINK_PROPERTIES=taskmanager.numberOfTaskSlots:2
    volumes:
      - ./target:/opt/flink/usrlib  # Optional: if you need to share JARs