version: '3.8'

services:
  jobmanager:
    image: flink:1.20.1-java17
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./target:/opt/flink/usrlib

  taskmanager:
    image: flink:1.20.1-java17
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./target:/opt/flink/usrlib
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - jobmanager
    environment:
      - FLINK_JOBMANAGER_ADDRESS=jobmanager
      - FLINK_JOBMANAGER_PORT=6123